// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceCenterReception.Data;

#nullable disable

namespace ServiceCenterReception.Migrations
{
    [DbContext(typeof(serviceCenterDbContext))]
    partial class serviceCenterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceCenterReception.Entity.CustomerProfile", b =>
                {
                    b.Property<long>("customerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("customerId"));

                    b.Property<DateTime>("DOB")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DOM")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("address")
                        .HasColumnType("text");

                    b.Property<long>("addressPinCode")
                        .HasColumnType("bigint");

                    b.Property<string>("customerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("dueInMonths")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("lastServiceDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("mobileNumber")
                        .HasColumnType("bigint");

                    b.HasKey("customerId");

                    b.HasIndex("mobileNumber")
                        .IsUnique();

                    b.ToTable("customerProfiles");
                });

            modelBuilder.Entity("ServiceCenterReception.Entity.FinalServiceBill", b =>
                {
                    b.Property<long>("finalServiceBillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("finalServiceBillId"));

                    b.Property<long>("amountPaid")
                        .HasColumnType("bigint");

                    b.Property<long>("customerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("dateTimeGenerated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("discountAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("discountPercentage")
                        .HasColumnType("bigint");

                    b.Property<long>("totalAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("vehicleServiceDetailId")
                        .HasColumnType("bigint");

                    b.HasKey("finalServiceBillId");

                    b.ToTable("finalServiceBills");
                });

            modelBuilder.Entity("ServiceCenterReception.Entity.ServiceCompletedTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TaskCharges")
                        .HasColumnType("integer");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("text");

                    b.Property<long?>("vehicleServiceDetailId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("vehicleServiceDetailId");

                    b.ToTable("ServiceCompletedTask");
                });

            modelBuilder.Entity("ServiceCenterReception.Entity.ServiceEstimationTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstimatedAmount")
                        .HasColumnType("integer");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskDescription")
                        .HasColumnType("text");

                    b.Property<long?>("vehicleServiceDetailId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("vehicleServiceDetailId");

                    b.ToTable("ServiceEstimationTask");
                });

            modelBuilder.Entity("ServiceCenterReception.Entity.ServiceTaskMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TaskCharges")
                        .HasColumnType("integer");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("serviceTaskMasters");
                });

            modelBuilder.Entity("ServiceCenterReception.Entity.VehicleDetails", b =>
                {
                    b.Property<long>("vehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("vehicleId"));

                    b.Property<long>("customerId")
                        .HasColumnType("bigint");

                    b.Property<string>("vehicleNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("vehicleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("vehicleId");

                    b.HasIndex("customerId");

                    b.ToTable("vehicleDetails");
                });

            modelBuilder.Entity("ServiceCenterReception.Entity.VehicleServiceDetail", b =>
                {
                    b.Property<long>("vehicleServiceDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("vehicleServiceDetailId"));

                    b.Property<long?>("VehicleServiceRecieveDeliveryId")
                        .HasColumnType("bigint");

                    b.Property<long>("customerId")
                        .HasColumnType("bigint");

                    b.Property<long>("vehicleId")
                        .HasColumnType("bigint");

                    b.HasKey("vehicleServiceDetailId");

                    b.HasIndex("VehicleServiceRecieveDeliveryId");

                    b.HasIndex("customerId");

                    b.ToTable("vehicleServiceDetails");
                });

            modelBuilder.Entity("ServiceCenterReception.Entity.VehicleServiceRecieveDelivery", b =>
                {
                    b.Property<long>("VehicleServiceRecieveDeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("VehicleServiceRecieveDeliveryId"));

                    b.Property<DateTime>("vehicleDeliveryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("vehicleReceiveDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("VehicleServiceRecieveDeliveryId");

                    b.ToTable("vehicleServiceRecieveDeliveries");
                });

            modelBuilder.Entity("ServiceCenterReception.Entity.ServiceCompletedTask", b =>
                {
                    b.HasOne("ServiceCenterReception.Entity.VehicleServiceDetail", null)
                        .WithMany("ServiceCompletedTasks")
                        .HasForeignKey("vehicleServiceDetailId");
                });

            modelBuilder.Entity("ServiceCenterReception.Entity.ServiceEstimationTask", b =>
                {
                    b.HasOne("ServiceCenterReception.Entity.VehicleServiceDetail", null)
                        .WithMany("ServiceEstimationTasks")
                        .HasForeignKey("vehicleServiceDetailId");
                });

            modelBuilder.Entity("ServiceCenterReception.Entity.VehicleDetails", b =>
                {
                    b.HasOne("ServiceCenterReception.Entity.CustomerProfile", "CustomerProfile")
                        .WithMany()
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerProfile");
                });

            modelBuilder.Entity("ServiceCenterReception.Entity.VehicleServiceDetail", b =>
                {
                    b.HasOne("ServiceCenterReception.Entity.VehicleServiceRecieveDelivery", "VehicleServiceRecieveDelivery")
                        .WithMany()
                        .HasForeignKey("VehicleServiceRecieveDeliveryId");

                    b.HasOne("ServiceCenterReception.Entity.CustomerProfile", "CustomerProfile")
                        .WithMany()
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerProfile");

                    b.Navigation("VehicleServiceRecieveDelivery");
                });

            modelBuilder.Entity("ServiceCenterReception.Entity.VehicleServiceDetail", b =>
                {
                    b.Navigation("ServiceCompletedTasks");

                    b.Navigation("ServiceEstimationTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
